package dit126.util.exception;

public class MultipleUsersFoundException extends Exception {

}
